languare: node_js
env:
  global:
    secure: OxBNQatq2PqM0xOkyoom4lQqJU7RDUJaHLPsUKEsgzjC0psnH3jiNshcGykkhWko5ysPFsI0BmxndtD/pYxKa7ei9rDuTd2we4KV9zz4RW7aczrG/24RlVsaalc3jKjQmg1lZ8ZF+GLLPeKviF4nU6RXhbxdjk8cPX8quIaG1fuj8B26QqWmZMmLHSRdTOCt++cDAR4WyIFbV4YHiDaFsHGZZM+107MSau1TEh2boD8bpQKi5MlngwXuzseKacNo7rm14QzDLF9dJlfy4E/q7cLB1iGoaQmTdjaxboQRWJ/I02u61LmQnb2weRlvT3W0V8d7+BfBv0qevtf4tK8IXJ9YMT2EPWQL3E2z1qnMr/lR7uY197iOfZtYnf2olFyamPXNvM4npN56pXQzY2jQOVSNr56wlxZFgTgD9OoepqYbGygJQSAghX0S6h5GgLOVIdeRzaWB/MlaUquxap/fuOgqTtrCDJXMju2BgZSx9MxQANbjNWQ/LKLoXfjf5jSLYyUizLx8C1VxlVNoOOIrWbqI8HfwpiWrwaJMRchK/45QIWln8hdfaDakoWDfEUfBzIkGSteKfj6YBkqjRExzZhzzQPIgKiDIHezVUqr+6zl0Vn2huNZTJHhAFK+JO/ednoKeFQQSOE581Nt0dFeIlgaCXAXX55Mp91KGjENbRVg=
branches:
  only:
    - master
node_js:
  - 12
cache: yarn
install:
  - bundle install
script:
  - yarn
  - yarn build
  - yarn test
  - yarn lint
  - bundle exec danger
deploy:
  provider: npm
  skip_cleanup: true
  email: app.nakayama@gmail.com
  api_key:
    secure: Tr5QfuFuSWOGP32AVpIbJ1Ytgevj8lLd2ovPqKxmvo9AJ3Lk0hcAMainr22A3ySFVuugGyGhmhD0E1BdMcE7Ia+NHzdipe1ttiuRN/K5ki6hbRBJpR/PZ9aytzRRea49HofSxxgfeTYY1ebk+FdMDZLqPhR6Usb/htapPFUjE7leIIzt4bQQLGPeeHG+5SoNizJS4YrqFgpX0mmIWpLd8ub9oNnM9d7F+C5t+mtJiPxtOlpPMmVur1V+Waafi98Egbt+YNifilYfRz8DGDvzRAFnM9q3JwcvPFK/3uRGA6RX34Nxk/CaKav3HOrVBwmwdg52Fa+oJbqujxe0vw4tEG9qk/4uMmFkW8+vlapfmlh4XvWUBJt7FLPKX/Opby1HCcIzWnF6vpksILpVRJeAbZtRNBcFR/qShhPQ4Mz134YI9S8z0KUbuT+5ldX3AJFfMthcUD+OcNFG3XHb6xf8IZOzgUix9I/kGEgGGVLN7YpDizXlNorqBRBjZIYvKHdfFy3egT363zhSa7AUk6ESBWWtf47f1Cb4uq6mMF4TdsnBzNp/Wec+8P4Ca4iqwKrXkHzDD6ueYnmQ9hGzgU0qyj9lm2zHHBDu9WHbKcHVSBY19UfB9GqpHmIuHgcSax7LwfG2GfG6ZPhm5EbXScqvkzP1ZvvUIqVACyL/kpBGbv8=
after_deploy:
  - "./scripts/release.sh"